name = "ugtktheme"
license = "MIT"
licenselink = "https://github.com/aws-user-group-toolkit/website/blob/main/LICENSE"
description = "Custom theme for AWS User Group Toolkit website"

# The home page of the theme, where the source can be found
homepage = "https://github.com/aws-user-group-toolkit/website"

# If you have a running demo of the theme
demosite = "https://usergroup-toolkit.com"

tags = ["responsive", "modern", "tailwind", "gradient", "dark"]
features = ["responsive", "tailwind", "dark mode", "blog", "gradient animations"]

[author]
  name = "Linda Mohamed"
  homepage = "https://www.linkedin.com/in/lindamohamed/"
